#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import time 

 st=time.time()fib=[1,2]

while fib[-1]+fib[-2] < 4E6:
	fib.append(fib[-1]+fib[-2])

print(fib)

sum = 0
for i in fib:
	if i%2==0:
		sum+=i
		print(str(sum)+" "+str(i))	

print("sum = "+str(sum))

end=time.time()

print('this code took ',str(end-st),' seconds to run')
